// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: member/v1/member.proto

package memberv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberStatus int32

const (
	MemberStatus_MEMBER_STATUS_UNSPECIFIED MemberStatus = 0
	MemberStatus_MEMBER_STATUS_PENDING     MemberStatus = 1
	MemberStatus_MEMBER_STATUS_ACTIVE      MemberStatus = 2
	MemberStatus_MEMBER_STATUS_SUSPENDED   MemberStatus = 3
)

// Enum value maps for MemberStatus.
var (
	MemberStatus_name = map[int32]string{
		0: "MEMBER_STATUS_UNSPECIFIED",
		1: "MEMBER_STATUS_PENDING",
		2: "MEMBER_STATUS_ACTIVE",
		3: "MEMBER_STATUS_SUSPENDED",
	}
	MemberStatus_value = map[string]int32{
		"MEMBER_STATUS_UNSPECIFIED": 0,
		"MEMBER_STATUS_PENDING":     1,
		"MEMBER_STATUS_ACTIVE":      2,
		"MEMBER_STATUS_SUSPENDED":   3,
	}
)

func (x MemberStatus) Enum() *MemberStatus {
	p := new(MemberStatus)
	*p = x
	return p
}

func (x MemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_member_v1_member_proto_enumTypes[0].Descriptor()
}

func (MemberStatus) Type() protoreflect.EnumType {
	return &file_member_v1_member_proto_enumTypes[0]
}

func (x MemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberStatus.Descriptor instead.
func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{0}
}

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
	Gender_GENDER_OTHER       Gender = 3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
		3: "GENDER_OTHER",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
		"GENDER_OTHER":       3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_member_v1_member_proto_enumTypes[1].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_member_v1_member_proto_enumTypes[1]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{1}
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Profile       *Profile               `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Status        MemberStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=member.v1.MemberStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_member_v1_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Member) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MEMBER_STATUS_UNSPECIFIED
}

func (x *Member) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Member) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        Gender                 `protobuf:"varint,4,opt,name=gender,proto3,enum=member.v1.Gender" json:"gender,omitempty"`
	Interests     []string               `protobuf:"bytes,5,rep,name=interests,proto3" json:"interests,omitempty"`
	PhotoUrls     []string               `protobuf:"bytes,6,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_member_v1_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Profile) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *Profile) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *Profile) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *Profile) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

type RegisterMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMemberRequest) Reset() {
	*x = RegisterMemberRequest{}
	mi := &file_member_v1_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMemberRequest) ProtoMessage() {}

func (x *RegisterMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMemberRequest.ProtoReflect.Descriptor instead.
func (*RegisterMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterMemberRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMemberResponse) Reset() {
	*x = RegisterMemberResponse{}
	mi := &file_member_v1_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMemberResponse) ProtoMessage() {}

func (x *RegisterMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMemberResponse.ProtoReflect.Descriptor instead.
func (*RegisterMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type AuthenticateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateMemberRequest) Reset() {
	*x = AuthenticateMemberRequest{}
	mi := &file_member_v1_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateMemberRequest) ProtoMessage() {}

func (x *AuthenticateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateMemberRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticateMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthenticateMemberRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateMemberResponse) Reset() {
	*x = AuthenticateMemberResponse{}
	mi := &file_member_v1_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateMemberResponse) ProtoMessage() {}

func (x *AuthenticateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateMemberResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenticateMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_member_v1_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{6}
}

func (x *GetMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type GetMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberResponse) Reset() {
	*x = GetMemberResponse{}
	mi := &file_member_v1_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberResponse) ProtoMessage() {}

func (x *GetMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberResponse.ProtoReflect.Descriptor instead.
func (*GetMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{7}
}

func (x *GetMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Profile       *Profile               `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_member_v1_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *UpdateProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_member_v1_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type ActivateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateMemberRequest) Reset() {
	*x = ActivateMemberRequest{}
	mi := &file_member_v1_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateMemberRequest) ProtoMessage() {}

func (x *ActivateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateMemberRequest.ProtoReflect.Descriptor instead.
func (*ActivateMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{10}
}

func (x *ActivateMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type ActivateMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateMemberResponse) Reset() {
	*x = ActivateMemberResponse{}
	mi := &file_member_v1_member_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateMemberResponse) ProtoMessage() {}

func (x *ActivateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_v1_member_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateMemberResponse.ProtoReflect.Descriptor instead.
func (*ActivateMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_v1_member_proto_rawDescGZIP(), []int{11}
}

func (x *ActivateMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

var File_member_v1_member_proto protoreflect.FileDescriptor

const file_member_v1_member_proto_rawDesc = "" +
	"\n" +
	"\x16member/v1/member.proto\x12\tmember.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x02\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12,\n" +
	"\aprofile\x18\x03 \x01(\v2\x12.member.v1.ProfileR\aprofile\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.member.v1.MemberStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe1\x01\n" +
	"\aProfile\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x129\n" +
	"\n" +
	"birth_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12)\n" +
	"\x06gender\x18\x04 \x01(\x0e2\x11.member.v1.GenderR\x06gender\x12\x1c\n" +
	"\tinterests\x18\x05 \x03(\tR\tinterests\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\x06 \x03(\tR\tphotoUrls\"I\n" +
	"\x15RegisterMemberRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\x16RegisterMemberResponse\x12)\n" +
	"\x06member\x18\x01 \x01(\v2\x11.member.v1.MemberR\x06member\"M\n" +
	"\x19AuthenticateMemberRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"G\n" +
	"\x1aAuthenticateMemberResponse\x12)\n" +
	"\x06member\x18\x01 \x01(\v2\x11.member.v1.MemberR\x06member\"/\n" +
	"\x10GetMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\">\n" +
	"\x11GetMemberResponse\x12)\n" +
	"\x06member\x18\x01 \x01(\v2\x11.member.v1.MemberR\x06member\"a\n" +
	"\x14UpdateProfileRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12,\n" +
	"\aprofile\x18\x02 \x01(\v2\x12.member.v1.ProfileR\aprofile\"B\n" +
	"\x15UpdateProfileResponse\x12)\n" +
	"\x06member\x18\x01 \x01(\v2\x11.member.v1.MemberR\x06member\"4\n" +
	"\x15ActivateMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"C\n" +
	"\x16ActivateMemberResponse\x12)\n" +
	"\x06member\x18\x01 \x01(\v2\x11.member.v1.MemberR\x06member*\x7f\n" +
	"\fMemberStatus\x12\x1d\n" +
	"\x19MEMBER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MEMBER_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14MEMBER_STATUS_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17MEMBER_STATUS_SUSPENDED\x10\x03*V\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02\x12\x10\n" +
	"\fGENDER_OTHER\x10\x032\xbc\x03\n" +
	"\rMemberService\x12U\n" +
	"\x0eRegisterMember\x12 .member.v1.RegisterMemberRequest\x1a!.member.v1.RegisterMemberResponse\x12a\n" +
	"\x12AuthenticateMember\x12$.member.v1.AuthenticateMemberRequest\x1a%.member.v1.AuthenticateMemberResponse\x12F\n" +
	"\tGetMember\x12\x1b.member.v1.GetMemberRequest\x1a\x1c.member.v1.GetMemberResponse\x12R\n" +
	"\rUpdateProfile\x12\x1f.member.v1.UpdateProfileRequest\x1a .member.v1.UpdateProfileResponse\x12U\n" +
	"\x0eActivateMember\x12 .member.v1.ActivateMemberRequest\x1a!.member.v1.ActivateMemberResponseBJZHgithub.com/mattuttis/inetcontrol/zoekdeware/api/proto/member/v1;memberv1b\x06proto3"

var (
	file_member_v1_member_proto_rawDescOnce sync.Once
	file_member_v1_member_proto_rawDescData []byte
)

func file_member_v1_member_proto_rawDescGZIP() []byte {
	file_member_v1_member_proto_rawDescOnce.Do(func() {
		file_member_v1_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_member_v1_member_proto_rawDesc), len(file_member_v1_member_proto_rawDesc)))
	})
	return file_member_v1_member_proto_rawDescData
}

var file_member_v1_member_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_member_v1_member_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_member_v1_member_proto_goTypes = []any{
	(MemberStatus)(0),                  // 0: member.v1.MemberStatus
	(Gender)(0),                        // 1: member.v1.Gender
	(*Member)(nil),                     // 2: member.v1.Member
	(*Profile)(nil),                    // 3: member.v1.Profile
	(*RegisterMemberRequest)(nil),      // 4: member.v1.RegisterMemberRequest
	(*RegisterMemberResponse)(nil),     // 5: member.v1.RegisterMemberResponse
	(*AuthenticateMemberRequest)(nil),  // 6: member.v1.AuthenticateMemberRequest
	(*AuthenticateMemberResponse)(nil), // 7: member.v1.AuthenticateMemberResponse
	(*GetMemberRequest)(nil),           // 8: member.v1.GetMemberRequest
	(*GetMemberResponse)(nil),          // 9: member.v1.GetMemberResponse
	(*UpdateProfileRequest)(nil),       // 10: member.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),      // 11: member.v1.UpdateProfileResponse
	(*ActivateMemberRequest)(nil),      // 12: member.v1.ActivateMemberRequest
	(*ActivateMemberResponse)(nil),     // 13: member.v1.ActivateMemberResponse
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
}
var file_member_v1_member_proto_depIdxs = []int32{
	3,  // 0: member.v1.Member.profile:type_name -> member.v1.Profile
	0,  // 1: member.v1.Member.status:type_name -> member.v1.MemberStatus
	14, // 2: member.v1.Member.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: member.v1.Member.updated_at:type_name -> google.protobuf.Timestamp
	14, // 4: member.v1.Profile.birth_date:type_name -> google.protobuf.Timestamp
	1,  // 5: member.v1.Profile.gender:type_name -> member.v1.Gender
	2,  // 6: member.v1.RegisterMemberResponse.member:type_name -> member.v1.Member
	2,  // 7: member.v1.AuthenticateMemberResponse.member:type_name -> member.v1.Member
	2,  // 8: member.v1.GetMemberResponse.member:type_name -> member.v1.Member
	3,  // 9: member.v1.UpdateProfileRequest.profile:type_name -> member.v1.Profile
	2,  // 10: member.v1.UpdateProfileResponse.member:type_name -> member.v1.Member
	2,  // 11: member.v1.ActivateMemberResponse.member:type_name -> member.v1.Member
	4,  // 12: member.v1.MemberService.RegisterMember:input_type -> member.v1.RegisterMemberRequest
	6,  // 13: member.v1.MemberService.AuthenticateMember:input_type -> member.v1.AuthenticateMemberRequest
	8,  // 14: member.v1.MemberService.GetMember:input_type -> member.v1.GetMemberRequest
	10, // 15: member.v1.MemberService.UpdateProfile:input_type -> member.v1.UpdateProfileRequest
	12, // 16: member.v1.MemberService.ActivateMember:input_type -> member.v1.ActivateMemberRequest
	5,  // 17: member.v1.MemberService.RegisterMember:output_type -> member.v1.RegisterMemberResponse
	7,  // 18: member.v1.MemberService.AuthenticateMember:output_type -> member.v1.AuthenticateMemberResponse
	9,  // 19: member.v1.MemberService.GetMember:output_type -> member.v1.GetMemberResponse
	11, // 20: member.v1.MemberService.UpdateProfile:output_type -> member.v1.UpdateProfileResponse
	13, // 21: member.v1.MemberService.ActivateMember:output_type -> member.v1.ActivateMemberResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_member_v1_member_proto_init() }
func file_member_v1_member_proto_init() {
	if File_member_v1_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_member_v1_member_proto_rawDesc), len(file_member_v1_member_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_member_v1_member_proto_goTypes,
		DependencyIndexes: file_member_v1_member_proto_depIdxs,
		EnumInfos:         file_member_v1_member_proto_enumTypes,
		MessageInfos:      file_member_v1_member_proto_msgTypes,
	}.Build()
	File_member_v1_member_proto = out.File
	file_member_v1_member_proto_goTypes = nil
	file_member_v1_member_proto_depIdxs = nil
}
